/**
 * ! Datos de prueba. Eliminar antes de pasar a producción
 */

export const people = [
  {
    name: "Admin",
    email: "admin@admin.com",
    rut: "11.111.111-1",
    password: "admin",
    role: "Admin",
  },
  {
    name: "Tandie",
    email: "temma0@salon.com",
    rut: "14.675.166-K",
    password: "fW7){Dnsj+BFC",
    role: "User",
  },
  {
    name: "Jareb",
    email: "jlachaize1@answers.com",
    rut: "10.784.699-6",
    password: "jQ4!v2A.}IMZ",
    role: "User",
  },
  {
    name: "Adela",
    email: "abeelby2@bbc.co.uk",
    rut: "17.544.111-6",
    password: "yD3.r8mO,",
    role: "User",
  },
  {
    name: "Lynnell",
    email: "lposvner3@time.com",
    rut: "20.286.476-K",
    password: "jR1@UFq!.Di+",
    role: "User",
  },
  {
    name: "Noam",
    email: "nolenechan4@wired.com",
    rut: "21.446.010-2",
    password: "gL5\\u3_xD=u1eRX>",
    role: "User",
  },
  {
    name: "Aimil",
    email: "ablaine5@booking.com",
    rut: "17.590.327-9",
    password: "qT8_C_D*'U|&0!G",
    role: "User",
  },
  {
    name: "Kele",
    email: "kpablo6@rakuten.co.jp",
    rut: "15.981.111-0",
    password: "tC0@9wDuW%!MM",
    role: "User",
  },
  {
    name: "Derril",
    email: "dcurrie7@howstuffworks.com",
    rut: "18.815.084-K",
    password: "oZ2+2\\{Nz",
    role: "User",
  },
  {
    name: "Freida",
    email: "fducker8@si.edu",
    rut: "15.593.072-1",
    password: "aJ7{?%(Cdo",
    role: "User",
  },
  {
    name: "Onfroi",
    email: "ohaborn9@msu.edu",
    rut: "20.696.482-K",
    password: "hZ8`JMW5u$PHOw",
    role: "User",
  },
  {
    name: "Waite",
    email: "wdarka@bluehost.com",
    rut: "20.348.088-9",
    companyRut: "32.449.375-8",
    password: "dM8.arYFhYTLx=fP",
    role: "Client",
  },
  {
    name: "Ara",
    email: "afellgettb@technorati.com",
    rut: "17.123.384-2",
    companyRut: "86.217.209-K",
    password: "cX8<!XR9$u",
    role: "Client",
  },
  {
    name: "Gabriello",
    email: "gpilgramc@ucoz.com",
    rut: "20.275.587-K",
    companyRut: "43.395.155-K",
    password: "nL3!iYN`_<h%,+sA",
    role: "Client",
  },
  {
    name: "Ramsey",
    email: "rposnerd@networkadvertising.org",
    rut: "21.050.766-2",
    companyRut: "43.297.504-K",
    password: "rX5.rR=rt1~AX?&",
    role: "Client",
  },
  {
    name: "Dalila",
    email: "djeppee@smh.com.au",
    rut: "21.972.627-K",
    companyRut: "77.909.564-7",
    password: 'mS7}jg80W}"Oi0',
    role: "Client",
  },
  {
    name: "Thornton",
    email: "tecobf@mtv.com",
    rut: "21.536.563-K",
    companyRut: "71.346.750-5",
    password: "rF1=PRPXeQ2Mb7k",
    role: "Client",
  },
  {
    name: "Randall",
    email: "rglasgowg@mozilla.com",
    rut: "13.204.610-9",
    companyRut: "72.877.301-5",
    password: "eO0!2\\gKHBDyc/$",
    role: "Client",
  },
  {
    name: "Sue",
    email: "salpineh@merriam-webster.com",
    rut: "21.074.872-7",
    companyRut: "68.950.774-K",
    password: "bP7.*_,yw}",
    role: "Client",
  },
  {
    name: "Therese",
    email: "tartinstalli@histats.com",
    rut: "19.787.535-K",
    companyRut: "45.587.402-9",
    password: "eC4|b4RtXH20d",
    role: "Client",
  },
  {
    name: "Drusilla",
    email: "dmccartyj@pinterest.com",
    rut: "15.886.788-K",
    companyRut: "99.734.771-K",
    password: "qA3+<lX8wqAA/",
    role: "Client",
  },
];
